// <auto-generated />
using System;
using Demen.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Demen.Content.Data.Migrations;

[DbContext(typeof(DemenContext))]
[Migration("20230903003922_Managers")]
partial class Managers
{
	/// <inheritdoc />
	protected override void BuildTargetModel(ModelBuilder modelBuilder)
	{
#pragma warning disable 612, 618
		modelBuilder
			.HasAnnotation("ProductVersion", "7.0.10")
			.HasAnnotation("Relational:MaxIdentifierLength", 63);

		NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

		modelBuilder.Entity("Demen.Content.Data.Entities.ManagerEntity", b =>
		{
			b.Property<int>("Id")
				.ValueGeneratedOnAdd()
				.HasColumnType("integer")
				.HasColumnName("id");

			NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

			b.Property<DateTime>("CreatedAt")
				.HasColumnType("timestamp with time zone")
				.HasColumnName("created_at");

			b.Property<DateTime?>("DeletedAt")
				.HasColumnType("timestamp with time zone")
				.HasColumnName("deleted_at");

			b.Property<string>("ExternalId")
				.IsRequired()
				.HasColumnType("varchar")
				.HasColumnName("external_id");

			b.Property<string>("Name")
				.IsRequired()
				.HasColumnType("varchar")
				.HasColumnName("name");

			b.Property<string>("Password")
				.IsRequired()
				.HasColumnType("varchar")
				.HasColumnName("password");

			b.Property<string>("StatusString")
				.IsRequired()
				.HasColumnType("varchar")
				.HasColumnName("status");

			b.Property<string>("Surname")
				.IsRequired()
				.HasColumnType("varchar")
				.HasColumnName("surname");

			b.Property<DateTime?>("UpdatedAt")
				.HasColumnType("timestamp with time zone")
				.HasColumnName("updated_at");

			b.HasKey("Id")
				.HasName("id");

			b.ToTable("managers", (string)null);
		});
#pragma warning restore 612, 618
	}
}
